apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmetic-api
  namespace: arithmetic
  labels:
    app: arithmetic-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arithmetic-api
  template:
    metadata:
      labels:
        app: arithmetic-api
    spec:
      containers:
        - name: api
          image: arithmetic-super-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: arithmetic-config
          env:
            - name: SECRET_KEY
              valueFrom: {secretKeyRef: {name: arithmetic-secrets, key: SECRET_KEY}}
            - name: JWT_SECRET
              valueFrom: {secretKeyRef: {name: arithmetic-secrets, key: JWT_SECRET}}
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet: {path: /api/health, port: 8000}
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: {path: /api/health, port: 8000}
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits:   {cpu: 500m, memory: 512Mi}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: arithmetic-data
