apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arithmetic.fullname" . }}-secrets
  labels:
    {{- include "arithmetic.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ include "arithmetic.secretKey" . | quote }}
  JWT_SECRET: {{ include "arithmetic.jwtSecret" . | quote }}
